platform :ios, '9.0'
use_frameworks!

target 'Petrel' do

  pod 'Moya/RxSwift'
  pod 'SwiftyJSON'
  pod "Moya-SwiftyJSONMapper/RxSwift"
  pod 'RxCocoa'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'AliyunOSSiOS', :git => 'https://gitee.com/raychow-github/aliyun-oss-ios-sdk.git'
  pod 'RxDataSources'
end

