platform :ios, '11.0'
use_frameworks!

target 'Petrel' do

  
  # only 64-bit build architecture from Pods targets
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        target.build_settings(configuration.name)['ARCHS'] = 'arm64 arm64e'
        target.build_settings(configuration.name)['VALID_ARCHS'] = 'arm64 arm64e'
      end
    end
  end

  pod 'Moya/RxSwift'
  pod "Moya-SwiftyJSONMapper/RxSwift"
  pod 'RxCocoa'
  pod 'RxDataSources'

  pod 'SwiftyJSON'
  
  pod 'MJRefresh'
  
  pod 'AliyunOSSiOS', :git => 'https://gitee.com/raychow-github/aliyun-oss-ios-sdk.git'
  
  pod 'IQKeyboardManagerSwift'
  
  pod 'SVProgressHUD'
  pod 'MBProgressHUD'

  pod 'FSPagerView'
  pod 'SKPhotoBrowser'
  # 布局
  pod 'SnapKit'
  # 图片
  pod 'Kingfisher'
  # realm
#  pod "RxRealm"
  pod 'RealmSwift'
  
  # router
  pod 'URLNavigator'
  
  # 选择器组件
#  pod 'BRPickerView'
#
#  pod 'GrowingTextView'

pod 'JXSegmentedView'

# 异步编程库
pod 'PromiseKit'
pod "PromiseKit/UIKit", "~> 6.0"


# 权限
#pod 'SPPermissions/Camera'
pod 'SPPermissions/PhotoLibrary'
#pod 'SPPermissions/Notification'
#pod 'SPPermissions/Microphone'
#pod 'SPPermissions/Calendar'
#pod 'SPPermissions/Contacts'
#pod 'SPPermissions/Reminders'
#pod 'SPPermissions/SpeechRecognizer'
#pod 'SPPermissions/Location'
#pod 'SPPermissions/Motion'
#pod 'SPPermissions/MediaLibrary'
#pod 'SPPermissions/Bluetooth'
#pod 'SPPermissions/Tracking'

end
