platform :ios, '9.0'
use_frameworks!

target 'Petrel' do

  pod 'Moya/RxSwift'
  pod "Moya-SwiftyJSONMapper/RxSwift"
  pod 'RxCocoa'
  pod 'RxDataSources'

  pod 'SwiftyJSON'
  
  pod 'MJRefresh'
  
  pod 'AliyunOSSiOS', :git => 'https://gitee.com/raychow-github/aliyun-oss-ios-sdk.git'
  
  pod 'IQKeyboardManagerSwift'
  
  pod 'SVProgressHUD'
  pod 'MBProgressHUD'

  pod 'FSPagerView'
  pod 'SKPhotoBrowser'
  # 布局
  pod 'SnapKit'
  # 图片
  pod 'Kingfisher'
  # realm
  pod "RxRealm"
  
  # router
  pod 'URLNavigator'
  
  # 选择器组件
#  pod 'BRPickerView'
#
#  pod 'GrowingTextView'

pod 'JXSegmentedView'

end

